version: "3"
services:
  spark-master:
    image: bde2020/spark-master:3.3.0-hadoop3.3
    container_name: spark-master
    working_dir: /spark
    volumes:
      - ./app:/spark/app
    ports:
      - "4040:4040"
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
      - SPARK_WORKER_INSTANCES=10

  spark-worker-1:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker-1
    working_dir: /spark
    depends_on:
      - spark-master
    volumes:
      - ./app:/spark/app
    ports:
      - "8081:8081"
      - "4041:4040"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - SPARK_WORKER_INSTANCES=10
  spark-worker-2:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker-2
    working_dir: /spark
    volumes:
      - ./app:/spark/app
    depends_on:
      - spark-master
    ports:
      - "8082:8082"
      - "4042:4040"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - SPARK_WORKER_INSTANCES=10
  spark-worker-3:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker-3
    working_dir: /spark
    volumes:
      - ./app:/spark/app
    depends_on:
      - spark-master
    ports:
      - "8083:8083"
      - "4043:4040"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - SPARK_WORKER_INSTANCES=10
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - 3306:3306 # HOST:CONTAINER
    environment:
      MYSQL_ROOT_PASSWORD: admin
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./data:/var/lib/mysql
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongodb:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1234
      - MONGO_INITDB_DATABASE=test
